menu:
  - name: Home
    url: /
  - name: Archives
    url: /archives
  - name: About
    url: /about
sidebar: # Sidebar
  enable: true 
  widgets:
    - search # Search
    - notice # Notice
    # - categories # Categories
    - tags # Tags
    - links # Links

  numlimit: # Limit the number of items shown in the sidebar
    categories: 5
    tags: 10
    
  links:
    - name: Bilibili
      url: https://space.bilibili.com/507635125?spm_id_from=333.1007.0.0
    - name: Github
      url: https://github.com/GarhinZhou
    - name: Email
      url: garhinzhou@163.com
    - name: Yuque
      url: https://www.yuque.com/garhin/furry
  notice: # 公告栏内容
    enable: true # 设置为 true 启用，false 禁用
    content: "欢迎来到Garhin的博客哇~文章来自本人语雀知识库~个人能力有限文章都是从语雀自动转移过来的，格式上会有点问题，而且也没法分类和加tag...但是搜索功能是正常的~" # 公告栏显示的内容

toc: #文章目录
  enable: true
